# -*- coding: utf-8 -*-
"""Harvard_python_library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPzPb4GNYnHHjZtxYcASI31D5SgTPzRt
"""

import random
coin = random.choice(["heads", "tails"])
print(coin)

from random import choice
coin = choice(["heads", "tails"])
print(coin)

import random
number = random.randint(1, 10)
print(number)

import random
card = ['ram', 'hari']
number = random.shuffle(card)
for car in card:
  print(car)

import statistics
print(statistics.mean([100, 90]))

import sys

try:
  print("hello, my name is", sys.argv[1])
except IndexError:
  print("Too few arguments")

#check for errors
if len(sys.argv)<2:
  print("Too few arguments")
elif len(sys.argv)>2:
  print("Too many arguments")
else:
  print('Hello, my name is', sys.argv[1])

if len(sys.argv)<2:
  print("Too few arguments")
for arg in sys.argv[1:]:
  print('Hello, my name is', arg)

pip install cowsay

import cowsay
import sys

if len(sys.argv) == 2:
  print(cowsay.cow('hello, ' + sys.argv[1]))

pip install requests

import json
import requests
import sys

if len(sys.argv) != 2:
  sys.exit()
response = requests.get("https://itunes.appple.com/search?entity=song&limit=50&term=" + sys.argv[1])
o = response.json()
for result in o["requests"]:
  print(result["trackName"])

import sys
from harvard_python_loop import hello

if len(sys.argv) == 2:
  hello(sys.argv[1])

